### ISSUE TITLE
No tooltip

### ISSUE THREAD

**Issue by KillyMXI** [gndclouds/days-since-obsidian#1]
Obsidian 1.5.12
Plugin version 1.0.0 from community plugins

Documentation doesn't specify whether date must be a link or text or code, but I tried all options and I can see no tooltip:

![days-since](https://github.com/gndclouds/days-since-obsidian/assets/13851064/4742898c-4f48-42c3-b6f0-79fd5d91d286)

I also spotted this error in developer console:

![image](https://github.com/gndclouds/days-since-obsidian/assets/13851064/9ff1ffa6-55a3-48bb-a593-5961b792de35)

Tried in sandbox vault - still no tooltip, and got this:

![image](https://github.com/gndclouds/days-since-obsidian/assets/13851064/11107ba5-51d6-470b-928f-2e5998b3115c)

**Comment by gndclouds** [comment]
hmm interesting, thanks for letting me know, the screenshots are super helpful. Will debug it this evening.

**Comment by gndclouds** [comment]
still working on this, i get the same issue in production but my testing env doesn't give the same Error so 'm trying to recreate it.

**Comment by gndclouds** [comment]
ok all is fixed in 2.0.3

![gndclouds 20240519-213409-Obsidian-1990-01-31 - ObsidianSandBox - Obsidian v1 6 0](https://github.com/gndclouds/days-since-obsidian/assets/1757261/29b41f01-3a6d-487c-beac-bd374b71257f)

**Comment by KillyMXI** [comment]
Thank you.
I can confirm that it works as shown above - right at the moment I select a date text.

I see some issues with this though.

The promise from the plugin description:

> This Obsidian plugin enhances your note-taking experience by providing a quick and intuitive way to track time. By simply hovering over any date in your notes, a tooltip appears, showing you how many days have passed since that date.

This seems to be inaccurate:
- selection is not very intuitive - I'm not aware of other extensions doing this;
- it is not quick and is not hovering - I need to do the selection;
- it is fiddly - tooltip disappears the moment I overshoot the selection.

When I found this plugin, I was looking for something that would be permanently on screen for links to daily notes and for specially formatted strings. Sad to see it is so far from that.
